In [2]:
import pandas as pd
import os
import sys

sys.path.append("../src")

from kpi_engineering import (
    build_absenteeism_kpi,
    build_learning_kpi,
    build_performance_kpi,
    build_engagement_kpi,
    build_talent_progression_kpi
)

CLEAN_PATH = "../data/clean"
OUTPUT_PATH = "../outputs"

In [4]:
hr = pd.read_csv(os.path.join(
    CLEAN_PATH,
    "20250218__Stats_CACEIS_EAE_EP_18_02_2025__Database.csv"
))

performance = pd.read_csv(os.path.join(
    CLEAN_PATH,
    "20240222__CACEIS_Notes_evaluation_2023__Feuil1.csv"
))

absences = pd.read_csv(os.path.join(
    CLEAN_PATH,
    "20260121__Absenteisme__detail_affectatio__extract.csv"
))

training = pd.read_csv(os.path.join(
    CLEAN_PATH,
    "Training_Records_Unnamed__Final_CSV.csv"
))

In [5]:
datasets = {
    "hr": hr,
    "performance": performance,
    "absences": absences,
    "training": training
}

for name, df in datasets.items():
    print(f"\n===== {name.upper()} =====")
    print("Shape:", df.shape)
    print(df.columns.tolist())
    display(df.head(3).T)

===== HR =====
Shape: (5766, 32)
['BU', ' Année', ' Nom du document', ' Statut du document', ' Evaluation manager', ' IUG', ' Nom', ' Prénom', ' Mail collaborateur', ' Libellé emploi', 'Type contrat', 'Code et libellé Service', " Nom de l'employeur légal", ' Code organisation niveau 05', ' Libellé Organisation niveau 05', ' Code organisation niveau 06', ' Libellé Organisation niveau 06', ' Code organisation niveau 07', ' Libellé Organisation niveau 07', ' Code organisation niveau 08', ' Libellé Organisation niveau 08', ' Code organisation niveau 09', ' Libellé Organisation niveau 09', ' Code organisation niveau 10', ' Libellé Organisation niveau 10', ' AUTO-ÉVALUATION IGNOREE', 'Note de performance', 'Pays', 'Statut', 'Country', 'Unnamed: 30', 'Statut.1']

,0,1,2
BU,CACEIS,CACEIS,CACEIS
Année,2024,2024,2024
Nom du document,Entretien professionnel 2024,A-Evaluation en responsabilité - Conformité 2024,D-Evaluation en responsabilité 2024
Statut du document,Entretien(s) terminé(s),Entretien(s) terminé(s),Entretien(s) terminé(s)
Evaluation manager,NaN,3 - A la hauteur des attentes,3 - A la hauteur des attentes
IUG,ANON_65X48X48X48X48X50X51X54X48X55X50X,ANON_65X48X48X48X48X50X51X54X48X55X50X,ANON_65X48X48X48X48X50X51X55X53X55X53X
Nom,XX,XX,XX
Prénom,XX,XX,XX
Mail collaborateur,XX,XX,XX
Libellé emploi,CHIEF COMPLIANCE OFFICER,CHIEF COMPLIANCE OFFICER,GLOBAL HEAD
Type contrat,CDI,CDI,CDI
Code et libellé Service,00351_C901C - Corporate Compliance,00351_C901C - Corporate Compliance,00351_R101C - Risk & Permanent Controls
Nom de l'employeur légal,00351 - CACEIS S.A.,00351 - CACEIS S.A.,00351 - CACEIS S.A.
Code organisation niveau 05,00351_SPC9A,00351_SPC9A,00351_SPR1A
Libellé Organisation niveau 05,SPF - Corporate Compliance,SPF - Corporate Compliance,SPF - Risk & Permanent Controls
Code organisation niveau 06,00351_C9CTB,00351_C9CTB,00351_R1RPB
Libellé Organisation niveau 06,Corporate Compliance,Corporate Compliance,Risk & Permanent Controls
Code organisation niveau 07,00351_C901C,00351_C901C,00351_R101C
Libellé Organisation niveau 07,Corporate Compliance,Corporate Compliance,Risk & Permanent Controls
Code organisation niveau 08,NaN,NaN,NaN
Libellé Organisation niveau 08,NaN,NaN,NaN
Code organisation niveau 09,NaN,NaN,NaN
Libellé Organisation niveau 09,NaN,NaN,NaN
Code organisation niveau 10,NaN,NaN,NaN
Libellé Organisation niveau 10,NaN,NaN,NaN
AUTO-ÉVALUATION IGNOREE,Non,Oui,Non
Note de performance,NaN,3.0,3.0
Pays,FR,FR,FR
Statut,Terminé,Terminé,Terminé
Country,France,France,France
Unnamed: 30,NaN,NaN,NaN
Statut.1,Auto-évaluation(s) collaborateur en cours,Entretiens(s) en cours manager,Entretien(s) terminé(s)

===== PERFORMANCE =====
Shape: (2544, 5)
['Pays', 'IUG', 'Nom', 'Contrat', 'Note']

,0,1,2
Pays,France,NaN,NaN
IUG,ANON_65X48X48X48X48X50X51X52X57X50X56X,ANON_65X48X48X48X48X50X51X54X48X55X50X,ANON_65X48X48X48X48X50X51X55X53X55X53X
Nom,XX,XX,XX
Contrat,CDI,CDI,CDI
Note,4,5,3

===== ABSENCES =====
Shape: (127825, 46)
['Mat compliance', 'Employee Code', 'Nom', 'Prénom', 'Genre', 'Type Contrat', 'Contrat Particulier', '* Concat Contrat', 'Présents/non Présents', 'Code Régime Temps Travail', 'Régime Temps Travail', 'Régime Temps Travail+', 'Code Société', 'Société', 'Code Niveau 6', 'Niveau 6', 'Code Niveau 7', 'Niveau 7', 'Code Niveau 8', 'Niveau 8', 'Code Niveau 9', 'Niveau 9', 'Code Organisation 1', 'Organisation 1', 'Code Organisation 2', 'Organisation 2', 'Code Organisation 3', 'Organisation 3', 'Code Organisation 4', 'Organisation 4', 'Code Organisation 5', 'Organisation 5', 'Code Organisation 6', 'Organisation 6', 'Code Organisation 7', 'Organisation 7', 'Code Organisation 8', 'Organisation 8', 'Date Absence', 'AAAA/MM Absence', 'Code Motif Jour Absence', 'Motif Jour Absence', 'Regroupement Jour Absences', 'Jour Calendaires Absence', 'Jours Ouvrables Absence', 'Jours Ouvrés Absence']

,0,1,2
Mat compliance,NaN,NaN,NaN
Employee Code,ANON_73X74X48X49X49X57X53X51X54X51X50X,ANON_73X74X48X49X49X57X53X51X54X51X50X,ANON_73X74X48X49X49X57X53X51X54X51X50X
Nom,XX,XX,XX
Prénom,XX,XX,XX
Genre,Masculin,Masculin,Masculin
Type Contrat,CDI,CDI,CDI
Contrat Particulier,NC,NC,NC
* Concat Contrat,CDINCStandard,CDINCStandard,CDINCStandard
Présents/non Présents,Présents,Présents,Présents
Code Régime Temps Travail,2,2,2
Régime Temps Travail,Cadre hors classe,Cadre hors classe,Cadre hors classe
Régime Temps Travail+,Cadres,Cadres,Cadres
Code Société,349,349,349
Société,CACEIS Bank,CACEIS Bank,CACEIS Bank
Code Niveau 6,BUI2A,BUI2A,BUI2A
Niveau 6,BUT - Information Technology,BUT - Information Technology,BUT - Information Technology
Code Niveau 7,I2COB,I2COB,I2COB
Niveau 7,IT Coverage,IT Coverage,IT Coverage
Code Niveau 8,I234C,I234C,I234C
Niveau 8,IT Coverage,IT Coverage,IT Coverage
Code Niveau 9,I2A0S,I2A0S,I2A0S
Niveau 9,Client demands,Client demands,Client demands
Code Organisation 1,CACEIS,CACEIS,CACEIS
Organisation 1,CACEIS,CACEIS,CACEIS
Code Organisation 2,B,B,B
Organisation 2,CACEIS BANK,CACEIS BANK,CACEIS BANK
Code Organisation 3,BBUI2A,BBUI2A,BBUI2A
Organisation 3,BUT - Information Technology,BUT - Information Technology,BUT - Information Technology
Code Organisation 4,BBUI2AI2COB,BBUI2AI2COB,BBUI2AI2COB
Organisation 4,IT Coverage,IT Coverage,IT Coverage
Code Organisation 5,BBUI2AI2COBI234C,BBUI2AI2COBI234C,BBUI2AI2COBI234C
Organisation 5,IT Coverage,IT Coverage,IT Coverage
Code Organisation 6,BBUI2AI2COBI234CI2A0S,BBUI2AI2COBI234CI2A0S,BBUI2AI2COBI234CI2A0S
Organisation 6,Client demands,Client demands,Client demands
Code Organisation 7,NC,NC,NC
Organisation 7,NaN,NaN,NaN
Code Organisation 8,NC,NC,NC
Organisation 8,NaN,NaN,NaN
Date Absence,2025-05-02,2025-05-30,2025-06-20
AAAA/MM Absence,2025/05,2025/05,2025/06
Code Motif Jour Absence,RECUP,RECUP,RECUP
Motif Jour Absence,Récupération,Récupération,Récupération
Regroupement Jour Absences,Congés,Congés,Congés
Jour Calendaires Absence,1.0,1.0,1.0
Jours Ouvrables Absence,1.0,1.0,1.0
Jours Ouvrés Absence,1.0,1.0,1.0

===== TRAINING =====
Shape: (14943, 12)
['Employee Code', 'Entity', 'Direction', 'Attended_Courses', 'Organization', 'Seesion_Start_Date', 'Session_End_Date', 'Session_ID', 'Status', 'Total_Training_Hours', 'Certifications', 'Year']

,0,1,2
Employee Code,NaN,NaN,NaN
Entity,NaN,CACEIS Bank,CACEIS Bank
Direction,NaN,NaN,NaN
Attended_Courses,Modèle de données GP4,2024 International compliance trainings,7Speaking plateforme licences annuelles
Organization,NEOXAM,IFCAM,7Speaking
Seesion_Start_Date,15/10/2025,29/11/2024,2025-06-01 00:00:00
Session_End_Date,17/10/2025,29/11/2024,2025-06-01 00:00:00
Session_ID,25-MDG-859-226,NaN,24-7PL-451-669
Status,Réalisé,Annulée,Réalisé
Total_Training_Hours,21.0,0.0,0.5
Certifications,No,No,No
Year,2025,2024,2025

In [6]:
def clean_cols(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("'", "", regex=False)
        .str.replace("é", "e")
        .str.replace("è", "e")
        .str.replace("ê", "e")
        .str.replace("/", "_")
    )
    return df

hr = clean_cols(hr)
performance = clean_cols(performance)
absences = clean_cols(absences)
training = clean_cols(training)

print(hr.columns.tolist())
print(performance.columns.tolist())
print(absences.columns.tolist())
print(training.columns.tolist())

['bu', 'annee', 'nom_du_document', 'statut_du_document', 'evaluation_manager', 'iug', 'nom', 'prenom', 'mail_collaborateur', 'libelle_emploi', 'type_contrat', 'code_et_libelle_service', 'nom_de_lemployeur_legal', 'code_organisation_niveau_05', 'libelle_organisation_niveau_05', 'code_organisation_niveau_06', 'libelle_organisation_niveau_06', 'code_organisation_niveau_07', 'libelle_organisation_niveau_07', 'code_organisation_niveau_08', 'libelle_organisation_niveau_08', 'code_organisation_niveau_09', 'libelle_organisation_niveau_09', 'code_organisation_niveau_10', 'libelle_organisation_niveau_10', 'auto-evaluation_ignoree', 'note_de_performance', 'pays', 'statut', 'country', 'unnamed:_30', 'statut.1']
['pays', 'iug', 'nom', 'contrat', 'note']
['mat_compliance', 'employee_code', 'nom', 'prenom', 'genre', 'type_contrat', 'contrat_particulier', '*_concat_contrat', 'presents_non_presents', 'code_regime_temps_travail', 'regime_temps_travail', 'regime_temps_travail+', 'code_societe', 'societe', 'code_niveau_6', 'niveau_6', 'code_niveau_7', 'niveau_7', 'code_niveau_8', 'niveau_8', 'code_niveau_9', 'niveau_9', 'code_organisation_1', 'organisation_1', 'code_organisation_2', 'organisation_2', 'code_organisation_3', 'organisation_3', 'code_organisation_4', 'organisation_4', 'code_organisation_5', 'organisation_5', 'code_organisation_6', 'organisation_6', 'code_organisation_7', 'organisation_7', 'code_organisation_8', 'organisation_8', 'date_absence', 'aaaa_mm_absence', 'code_motif_jour_absence', 'motif_jour_absence', 'regroupement_jour_absences', 'jour_calendaires_absence', 'jours_ouvrables_absence', 'jours_ouvres_absence']
['employee_code', 'entity', 'direction', 'attended_courses', 'organization', 'seesion_start_date', 'session_end_date', 'session_id', 'status', 'total_training_hours', 'certifications', 'year']

In [7]:
HR_ID = "iug"
PERFORMANCE_ID = "iug"
PERFORMANCE_SCORE = "note"

ABSENCE_ID = "employee_code"
ABSENCE_DAYS = "jours_ouvres_absence"

TRAINING_ID = "employee_code"
TRAINING_HOURS = "total_training_hours"
TRAINING_SESSION = "session_id"
TRAINING_DATE = "seesion_start_date"

In [14]:
performance[PERFORMANCE_SCORE] = pd.to_numeric(performance[PERFORMANCE_SCORE], errors="coerce")

performance_kpi = (
    performance
    .dropna(subset=[PERFORMANCE_ID])
    .groupby(PERFORMANCE_ID)
    .agg(
        avg_performance=(PERFORMANCE_SCORE, "mean"),
        performance_std=(PERFORMANCE_SCORE, "std"),
        performance_reviews=(PERFORMANCE_SCORE, "count")
    )
    .reset_index()
)

In [15]:
# Fix missing std (1 review case)
performance_kpi["performance_std"] = performance_kpi["performance_std"].fillna(0)

# Flag low data reliability
performance_kpi["low_data_flag"] = performance_kpi["performance_reviews"] < 2

In [16]:
performance_kpi["performance_consistency_score"] = (
    1 - performance_kpi["performance_std"].rank(pct=True)
)

performance_kpi["performance_consistency_score"] = (
    performance_kpi["performance_consistency_score"].fillna(1)
)

performance_kpi.head()

,iug,avg_performance,performance_std,performance_reviews,low_data_flag,performance_consistency_score
0,ANON_65X48X48X48X48X50X51X52X57X50X56X,4.0,0.0,1,True,0.499803
1,ANON_65X48X48X48X48X50X51X54X48X55X50X,5.0,0.0,1,True,0.499803
2,ANON_65X48X48X48X48X50X51X55X53X55X53X,3.0,0.0,1,True,0.499803
3,ANON_65X48X48X48X48X50X51X57X56X56X53X,3.0,0.0,1,True,0.499803
4,ANON_65X48X48X48X50X53X48X49X50X52X55X,3.0,0.0,1,True,0.499803

In [17]:
absences[ABSENCE_DAYS] = pd.to_numeric(absences[ABSENCE_DAYS], errors="coerce")

absence_kpi = (
    absences
    .dropna(subset=[ABSENCE_ID])
    .groupby(ABSENCE_ID)
    .agg(
        absence_events=(ABSENCE_ID, "count"),
        absence_days=(ABSENCE_DAYS, "sum")
    )
    .reset_index()
)

absence_kpi["absence_events_score"] = absence_kpi["absence_events"].rank(pct=True)
absence_kpi["absence_days_score"] = absence_kpi["absence_days"].rank(pct=True)

absence_kpi["absenteeism_risk_score"] = (
    0.4 * absence_kpi["absence_events_score"] +
    0.6 * absence_kpi["absence_days_score"]
)

absence_kpi.head()

,employee_code,absence_events,absence_days,absence_events_score,absence_days_score,absenteeism_risk_score
0,ANON_65X48X48X48X48X50X51X54X48X55X50X,32,26.0,0.214664,0.214443,0.214532
1,ANON_65X48X48X48X48X50X51X55X53X55X53X,42,31.5,0.398410,0.305433,0.342624
2,ANON_65X48X48X48X48X50X51X57X56X56X53X,46,39.0,0.505521,0.545053,0.529240
3,ANON_65X48X48X48X50X53X48X49X50X52X55X,40,29.5,0.348057,0.265018,0.298233
4,ANON_65X48X48X48X50X53X48X49X53X52X48X,47,34.5,0.532023,0.389576,0.446555

In [18]:
training[TRAINING_HOURS] = pd.to_numeric(training[TRAINING_HOURS], errors="coerce")

training_kpi = (
    training
    .dropna(subset=[TRAINING_ID])
    .groupby(TRAINING_ID)
    .agg(
        training_count=(TRAINING_SESSION, "count"),
        training_hours=(TRAINING_HOURS, "sum")
    )
    .reset_index()
)

training_kpi["training_count_score"] = training_kpi["training_count"].rank(pct=True)
training_kpi["training_hours_score"] = training_kpi["training_hours"].rank(pct=True)

training_kpi["learning_intensity_score"] = (
    0.5 * training_kpi["training_count_score"] +
    0.5 * training_kpi["training_hours_score"]
)

training_kpi.head()

,employee_code,training_count,training_hours,training_count_score,training_hours_score,learning_intensity_score
0,ANON_65X48X48X48X48X50X51X54X48X55X50X,2,63.00,0.351330,0.706487,0.528908
1,ANON_65X48X48X48X48X50X51X55X53X55X53X,1,14.00,0.154714,0.388799,0.271757
2,ANON_65X48X48X48X48X50X51X57X56X56X53X,8,65.00,0.778606,0.716761,0.747683
3,ANON_65X48X48X48X50X53X48X49X53X52X48X,11,70.46,0.867446,0.739726,0.803586
4,ANON_65X48X48X48X50X53X48X51X49X50X57X,9,65.50,0.812047,0.719380,0.765713

In [19]:
talent_progression = (
    hr
    .dropna(subset=[HR_ID])
    .groupby(HR_ID)
    .agg(
        document_count=("nom_du_document", "count"),
        role=("libelle_emploi", "first"),
        contract_type=("type_contrat", "first"),
        country=("country", "first"),
        business_unit=("bu", "first")
    )
    .reset_index()
)

talent_progression["talent_progression_proxy"] = (
    talent_progression["document_count"].rank(pct=True)
)

talent_progression.head()

,iug,document_count,role,contract_type,country,business_unit,talent_progression_proxy
0,ANON_65X48X48X48X48X50X51X54X48X55X50X,2,CHIEF COMPLIANCE OFFICER,CDI,France,CACEIS,0.735325
1,ANON_65X48X48X48X48X50X51X55X53X55X53X,2,GLOBAL HEAD,CDI,France,CACEIS,0.735325
2,ANON_65X48X48X48X48X50X51X57X56X56X53X,2,GROUP HEAD,CDI,France,CACEIS,0.735325
3,ANON_65X48X48X48X50X53X48X49X50X52X55X,2,GENERAL SECRETARY,CDI,France,CACEIS,0.735325
4,ANON_65X48X48X48X50X53X48X49X53X52X48X,2,IT PROJECT LEAD,CDI,France,CACEIS,0.735325

In [20]:
hr_base = (
    hr
    .dropna(subset=[HR_ID])
    .drop_duplicates(subset=[HR_ID])
    [[HR_ID, "bu", "libelle_emploi", "type_contrat", "country", "libelle_organisation_niveau_07"]]
)

hr_kpi_table = hr_base.merge(
    performance_kpi,
    left_on=HR_ID,
    right_on=PERFORMANCE_ID,
    how="left"
)

hr_kpi_table = hr_kpi_table.merge(
    talent_progression[[HR_ID, "talent_progression_proxy"]],
    on=HR_ID,
    how="left"
)

hr_kpi_table.head()

,iug,bu,libelle_emploi,type_contrat,country,libelle_organisation_niveau_07,avg_performance,performance_std,performance_reviews,low_data_flag,performance_consistency_score,talent_progression_proxy
0,ANON_65X48X48X48X48X50X51X54X48X55X50X,CACEIS,CHIEF COMPLIANCE OFFICER,CDI,France,Corporate Compliance,5.0,0.0,1.0,True,0.499803,0.735325
1,ANON_65X48X48X48X48X50X51X55X53X55X53X,CACEIS,GLOBAL HEAD,CDI,France,Risk & Permanent Controls,3.0,0.0,1.0,True,0.499803,0.735325
2,ANON_65X48X48X48X48X50X51X57X56X56X53X,CACEIS,GROUP HEAD,CDI,France,Enterprise Architecture,3.0,0.0,1.0,True,0.499803,0.735325
3,ANON_65X48X48X48X50X53X48X49X50X52X55X,CACEIS,GENERAL SECRETARY,CDI,France,General Secretary & Controls,3.0,0.0,1.0,True,0.499803,0.735325
4,ANON_65X48X48X48X50X53X48X49X53X52X48X,CACEIS,IT PROJECT LEAD,CDI,France,IT Risks & CRM,4.0,0.0,1.0,True,0.499803,0.735325

In [21]:
hr_kpi_table.to_csv("../outputs/hr_kpi_table.csv", index=False, encoding="utf-8-sig")
absence_kpi.to_csv("../outputs/absence_kpi_table.csv", index=False, encoding="utf-8-sig")
training_kpi.to_csv("../outputs/training_kpi_table.csv", index=False, encoding="utf-8-sig")

print("KPI tables saved successfully.")

KPI tables saved successfully.

Important limitation: HR/performance data uses `IUG`, while absenteeism and training use `Employee Code`. Since these identifiers do not appear to match directly, we avoid unsafe merges. Absenteeism and learning KPIs are therefore calculated in separate employee-level tables, while the main HR KPI table combines HR and performance data through `IUG`.

In [22]:
performance_kpi.head()

,iug,avg_performance,performance_std,performance_reviews,low_data_flag,performance_consistency_score
0,ANON_65X48X48X48X48X50X51X52X57X50X56X,4.0,0.0,1,True,0.499803
1,ANON_65X48X48X48X48X50X51X54X48X55X50X,5.0,0.0,1,True,0.499803
2,ANON_65X48X48X48X48X50X51X55X53X55X53X,3.0,0.0,1,True,0.499803
3,ANON_65X48X48X48X48X50X51X57X56X56X53X,3.0,0.0,1,True,0.499803
4,ANON_65X48X48X48X50X53X48X49X50X52X55X,3.0,0.0,1,True,0.499803